// <auto-generated />
namespace CleanArchTemplate.BC.Home.Domain.Persistence.UOW.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class HomeDbContextConfigurationInitialModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HomeDbContextConfigurationInitialModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201909171306463_HomeDbContextConfigurationInitialModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
